AWSTemplateFormatVersion: '2010-09-09'
Description: 'Flash Sale Project - Phase 1: High Availability Network Layer'

Resources:
  # 1. The Core VPC
  FlashSaleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: FlashSale-VPC

  # 2. The Internet Doorway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: FlashSale-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FlashSaleVPC
      InternetGatewayId: !Ref InternetGateway

  # 3. Public Subnets (For the Load Balancer)
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FlashSaleVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ''] 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: FlashSale-Public-Subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FlashSaleVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ''] 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: FlashSale-Public-Subnet-2

  # 4. Private Subnets (For the Web Servers & Database)
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FlashSaleVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: FlashSale-Private-Subnet-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FlashSaleVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: FlashSale-Private-Subnet-2

Outputs:
  VpcId:
    Description: The ID of the VPC
    Value: !Ref FlashSaleVPC
    Export:
      Name: FlashSale-VpcId
  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
    Export:
      Name: FlashSale-PublicSubnet1
  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
    Export:
      Name: FlashSale-PublicSubnet2